"""Add default UUID to chat_session.session_id

Revision ID: 1f8d70a93519
Revises: b7b7ca14b957
Create Date: 2026-02-15 18:22:09.106690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f8d70a93519"
down_revision: Union[str, Sequence[str], None] = "b7b7ca14b957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_session_created_at"), table_name="chat_message", schema="test"
    )
    op.create_index(
        "idx_session_created_at",
        "chat_message",
        [sa.literal_column("session_id, created_at ASC")],
        unique=False,
        schema="test",
    )
    op.drop_index(op.f("idx_user_updated_at"), table_name="chat_session", schema="test")
    op.create_index(
        "idx_user_updated_at",
        "chat_session",
        [sa.literal_column("user_id, updated_at DESC")],
        unique=False,
        schema="test",
    )

    # Add default UUID generation to session_id column
    op.execute(
        "ALTER TABLE test.chat_session ALTER COLUMN session_id SET DEFAULT uuid_generate_v4();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_updated_at", table_name="chat_session", schema="test")
    op.create_index(
        op.f("idx_user_updated_at"),
        "chat_session",
        ["user_id", sa.literal_column("updated_at DESC")],
        unique=False,
        schema="test",
    )
    op.drop_index("idx_session_created_at", table_name="chat_message", schema="test")
    op.create_index(
        op.f("idx_session_created_at"),
        "chat_message",
        ["session_id", "created_at"],
        unique=False,
        schema="test",
    )
    # ### end Alembic commands ###
