"""Add chat app tables to test schema

Revision ID: b7b7ca14b957
Revises:
Create Date: 2026-02-15 16:02:32.343732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7b7ca14b957"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable uuid-ossp extension for UUID generation
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')

    op.create_table(
        "user",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        schema="test",
    )
    op.create_table(
        "chat_session",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), server_default="New Chat", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["test.user.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
        schema="test",
    )
    op.create_index(
        "idx_user_updated_at",
        "chat_session",
        [sa.literal_column("user_id, updated_at DESC")],
        unique=False,
        schema="test",
    )
    op.create_table(
        "chat_message",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["test.chat_session.session_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
        schema="test",
    )
    op.create_index(
        "idx_session_created_at",
        "chat_message",
        [sa.literal_column("session_id, created_at ASC")],
        unique=False,
        schema="test",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_session_created_at", table_name="chat_message", schema="test")
    op.drop_table("chat_message", schema="test")
    op.drop_index("idx_user_updated_at", table_name="chat_session", schema="test")
    op.drop_table("chat_session", schema="test")
    op.drop_table("user", schema="test")
    # ### end Alembic commands ###
